// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyB7nEZ3tFvCkjRLW426KVyiUUoLq9m9r3c',
    appId: '1:901188157779:web:7799d65737b0d50654a1a6',
    messagingSenderId: '901188157779',
    projectId: 'sgym-4912a',
    authDomain: 'sgym-4912a.firebaseapp.com',
    storageBucket: 'sgym-4912a.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDEa6EbD9Jt2siTDZyAkeL-I7UQjgjaYl4',
    appId: '1:901188157779:android:c5c50d4e272ec2d754a1a6',
    messagingSenderId: '901188157779',
    projectId: 'sgym-4912a',
    storageBucket: 'sgym-4912a.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDQWK7LZCqt62X2GzNZ6boLBBjG4Ij_VWc',
    appId: '1:901188157779:ios:401767284df2dd2654a1a6',
    messagingSenderId: '901188157779',
    projectId: 'sgym-4912a',
    storageBucket: 'sgym-4912a.firebasestorage.app',
    iosBundleId: 'com.example.agym',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDQWK7LZCqt62X2GzNZ6boLBBjG4Ij_VWc',
    appId: '1:901188157779:ios:401767284df2dd2654a1a6',
    messagingSenderId: '901188157779',
    projectId: 'sgym-4912a',
    storageBucket: 'sgym-4912a.firebasestorage.app',
    iosBundleId: 'com.example.agym',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyB7nEZ3tFvCkjRLW426KVyiUUoLq9m9r3c',
    appId: '1:901188157779:web:7448513153bcec3c54a1a6',
    messagingSenderId: '901188157779',
    projectId: 'sgym-4912a',
    authDomain: 'sgym-4912a.firebaseapp.com',
    storageBucket: 'sgym-4912a.firebasestorage.app',
  );
}
